In [1]:
import numpy  as np

### input data

In [2]:
a = np.array([0, 1, 2, 3]) #vector

b = np.array([4,5,6,7])#vector

c = np.array([[0,1,2,3], #matrix
             [4,5,6,7]]) 

d = np.array((2,4)) # 2*4 matrix of zeros

e = np.random.rand(2,5) #Random 2*5 matrix

In [3]:
print("a  ",a )
print("b  ",b)
print("c  ",c)
print("d  ",d)

print("e  ",e)

a   [0 1 2 3]
b   [4 5 6 7]
c   [[0 1 2 3]
 [4 5 6 7]]
d   [2 4]
e   [[0.08646617 0.08705897 0.7172331  0.24529744 0.12227804]
 [0.92292551 0.28807875 0.85463186 0.63182603 0.64179518]]


### operation on input

In [4]:
print("a * 0.1 =",a * 0.1)
print("a * 0.2 =",a * 0.2)
print("a * b =",a * b)
print("a * b * 0.2=",a * b * 0.2)
print("a * c =",a * c)
#print("a * e =",a * e)#produces a ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

a * 0.1 = [0.  0.1 0.2 0.3]
a * 0.2 = [0.  0.2 0.4 0.6]
a * b = [ 0  5 12 21]
a * b * 0.2= [0.  1.  2.4 4.2]
a * c = [[ 0  1  4  9]
 [ 0  5 12 21]]


### matrix multiplication examples 

In [5]:
#inputs ()
a = np.zeros((1,4))
b = np.zeros((4,3))

In [6]:
#mul operations (the number of rows and columns must lineup)
c = a.dot(b) #vector of length 4


In [7]:
print(c.shape) #matrix of 4*3

(1, 3)


In [8]:
                    # R * C
e = np.zeros((2,1)) # 2 * 1 matrix
f = np.zeros((1,3)) # 1*3 matrix

### mul operation

In [9]:
g = e.dot(f)


In [10]:
print(g.shape) #2 * 3 matrix

(2, 3)


In [11]:
h = np.zeros((5,4)).T #5*4 matrix --throws an error when mul by i ; T flips the Rows and columns of a matrix(to 6*5 marix)
i = np.zeros((5,6)) #5*6 matrix

In [12]:
j = h.dot(i)
print(j.shape) # output: 4*6 matrix

(4, 6)
